import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
const output=path.resolve('tests/output');await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.TRACE3D_BROWSER_EXECUTABLE?{executablePath:process.env.TRACE3D_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});
const errors=[];
const url='file://'+path.resolve('dist/index.html');
async function open(locale,options={}){const page=await browser.newPage({locale,viewport:{width:1440,height:1080},...options});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('.part-item').length===4);return page;}
async function save(page){const event=page.waitForEvent('download');await page.locator('#saveProject').click();const download=await event;return JSON.parse(await fs.readFile(await download.path(),'utf8'));}
try{
 for(const [locale,lang,label] of [['nl-NL','nl','Voorbeeld'],['en-US','en','Example'],['de-DE','de','Beispiel'],['fr-CA','fr','Exemple']]){const p=await open(locale);assert.equal(await p.locator('html').getAttribute('lang'),lang);assert.equal(await p.locator('#loadDemo').textContent(),label);await p.close();}
 const page=await open('en-US');await page.locator('#languageSelect').selectOption('de');assert.equal(await page.locator('#loadDemo').textContent(),'Beispiel');await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.part-item').length===4);assert.equal(await page.locator('html').getAttribute('lang'),'de');await page.locator('#languageSelect').selectOption('nl');
 await page.locator('.part-item').first().click();await page.locator('#partHeight').fill('6');await page.locator('#partHeight').dispatchEvent('change');await page.waitForFunction(()=>document.getElementById('modelSize').textContent.endsWith('6 mm'));let project=await save(page);assert.equal(project.shapes.filter(s=>s.height===6).length,1);
 await page.locator('.layer-row input[type=checkbox]').nth(0).check();await page.locator('.layer-row input[type=checkbox]').nth(1).check();await page.locator('#groupLayers').click();assert.equal(await page.locator('.group-heading').count(),1);project=await save(page);assert.equal(project.groups.length,1);assert.equal(project.shapes.filter(s=>s.groupId===project.groups[0].id).length,2);
 await page.locator('#undo').click();assert.equal(await page.locator('.group-heading').count(),0);await page.locator('#redo').click();assert.equal(await page.locator('.group-heading').count(),1);
 await page.locator('.group-heading').click();await page.locator('#partHeight').fill('5');await page.locator('#partHeight').dispatchEvent('change');project=await save(page);assert.equal(project.shapes.filter(s=>s.groupId&&s.height===5).length,2);
 // Clicking an individual grouped row edits only that layer.
 await page.locator('.grouped .part-item').first().click();await page.locator('#partHeight').fill('7');await page.locator('#partHeight').dispatchEvent('change');project=await save(page);assert.equal(project.shapes.filter(s=>s.height===7).length,1);assert.equal(project.shapes.filter(s=>s.height===5).length,1);
 const beforeMove=structuredClone(project);const canvas=await page.locator('#drawing').boundingBox();const x=canvas.x+canvas.width*.5,y=canvas.y+canvas.height*.53;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+20,y+12,{steps:5});await page.mouse.up();project=await save(page);const grouped=project.shapes.filter(s=>s.groupId);for(const s of grouped){const previous=beforeMove.shapes.find(p=>p.id===s.id);assert.notDeepEqual(s.polygons,previous.polygons);}const deltas=grouped.map(s=>{const previous=beforeMove.shapes.find(p=>p.id===s.id);return s.polygons[0][0].map((v,i)=>v-previous.polygons[0][0][i]);});assert.ok(Math.abs(deltas[0][0]-deltas[1][0])<1e-6);assert.ok(Math.abs(deltas[0][1]-deltas[1][1])<1e-6);
 await page.locator('#projectFile').setInputFiles({name:'relief.trace3d.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.locator('#acceptConfirm').click();let reopened=await save(page);assert.equal(reopened.groups.length,1);assert.deepEqual(reopened.shapes.map(s=>s.height),project.shapes.map(s=>s.height));assert.equal(reopened.shapes.filter(s=>s.groupId).length,2);
 await page.locator('[data-format="obj"]').click();{const event=page.waitForEvent('download');await page.locator('#exportModel').click();const download=await event,zip=await JSZip.loadAsync(await fs.readFile(await download.path()));const obj=await zip.file(/\.obj$/)[0].async('string'),mtl=await zip.file(/\.mtl$/)[0].async('string');assert.ok(obj.includes('usemtl color_'));assert.ok(obj.includes('\nv '));assert.ok(mtl.includes('Kd '));assert.ok(!mtl.includes('map_Kd'));assert.equal(zip.file(/\.png$/).length,0);}
 await page.locator('.group-heading').click();await page.locator('#ungroupLayers').click();assert.equal(await page.locator('.group-heading').count(),0);await page.locator('#undo').click();assert.equal(await page.locator('.group-heading').count(),1);
 await page.locator('#projectName').fill('Mijn eigen naam');await page.locator('#languageSelect').selectOption('fr');assert.equal(await page.locator('#projectName').inputValue(),'Mijn eigen naam');assert.equal(await page.locator('#loadDemo').textContent(),'Exemple');assert.equal(await page.locator('[data-tool=fill] span').textContent(),'Remplir');assert.equal(await page.locator('#exportModel span').textContent(),'Télécharger le paquet OBJ');
 const mobile=await open('en-US',{viewport:{width:390,height:844},isMobile:true,hasTouch:true});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobile.locator('#languageSelect').selectOption('fr');assert.equal(await mobile.locator('html').getAttribute('lang'),'fr');assert.equal(await mobile.locator('#previewUnavailable').isVisible(),false);
 // Backwards compatibility: legacy v1 projects have no layer heights or groups.
 const legacy={...project,version:1};delete legacy.groups;legacy.shapes=legacy.shapes.map(({height,groupId,...layer})=>layer);await page.locator('#projectFile').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.locator('#acceptConfirm').click();const old=await save(page);assert.equal(old.groups.length,0);assert.ok(old.shapes.every(s=>s.height===undefined&&s.groupId===undefined));
 await mobile.screenshot({path:path.join(output,'mobile-v02.png'),fullPage:true});
 // Native touch regression: no pointer capture, no scrolling, no duplicate strokes.
 await mobile.locator('#newProject').click();await mobile.locator('#acceptConfirm').click();await mobile.locator('#drawingWrap').evaluate(el=>{el.setPointerCapture=()=>{throw new Error('Pointer capture unavailable');};});
 const cdp=await mobile.context().newCDPSession(mobile);
 async function touch(type,points){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
 async function drawTouch(coordinates){await mobile.locator('#drawing').scrollIntoViewIfNeeded();const box=await mobile.locator('#drawing').boundingBox(),points=coordinates.map(([x,y])=>({x:box.x+x*box.width,y:box.y+y*box.height,id:1})),scroll=await mobile.evaluate(()=>scrollY);await touch('touchStart',[points[0]]);for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];for(let k=1;k<=10;k++)await touch('touchMove',[{id:1,x:a.x+(b.x-a.x)*k/10,y:a.y+(b.y-a.y)*k/10}]);}await touch('touchEnd',[]);assert.equal(await mobile.evaluate(()=>scrollY),scroll);}
 await drawTouch([[.2,.2],[.8,.2],[.8,.8],[.2,.8],[.2,.2]]);assert.equal(await mobile.locator('.part-item').count(),1);await mobile.locator('[data-tool=fill]').click();await drawTouch([[.5,.5]]);assert.equal(await mobile.locator('.part-item').count(),2);
 await mobile.locator('[data-tool=pen]').click();await mobile.locator('#drawing').scrollIntoViewIfNeeded();const b=await mobile.locator('#drawing').boundingBox(),finger={id:1,x:b.x+b.width*.3,y:b.y+b.height*.3},second={id:2,x:b.x+b.width*.7,y:b.y+b.height*.7};await touch('touchStart',[finger]);await touch('touchMove',[{...finger,x:finger.x+20}]);await touch('touchCancel',[]);assert.equal(await mobile.locator('.part-item').count(),2);await touch('touchStart',[finger]);await touch('touchStart',[finger,second]);await touch('touchMove',[{...finger,x:finger.x-20},{...second,x:second.x+20}]);await touch('touchEnd',[]);assert.equal(await mobile.locator('.part-item').count(),2);assert.notEqual(await mobile.locator('#fitView').textContent(),'100%');
 await page.locator('#preview3d').screenshot({path:path.join(output,'preview-relief.png')});assert.deepEqual(errors,[]);
 console.log('Browser checks passed: four automatic locales, persisted language switch, individual and group heights, grouping/moving/undo/reopen, multipart OBJ and mobile layout.');
}finally{await browser.close();}
