import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
const browser=await chromium.launch({headless:true,...(process.env.TRACE3D_BROWSER_EXECUTABLE?{executablePath:process.env.TRACE3D_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});
const errors=[],url='file://'+path.resolve('dist/index.html');
const context=await browser.newContext({locale:'nl-NL',viewport:{width:1440,height:1120}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function saved(){await page.waitForFunction(()=>document.getElementById('autosaveStatus').textContent.includes('Automatisch opgeslagen'));}
async function project(){const event=page.waitForEvent('download');await page.locator('#saveProject').click();const d=await event;return JSON.parse(await fs.readFile(await d.path(),'utf8'));}
async function blank(){await page.locator('#newProject').click();if(await page.locator('#confirmDialog').isVisible())await page.locator('#acceptConfirm').click();assert.equal(await page.locator('.part-item').count(),0);}
async function drag(tool,a,b,options={}){await page.locator(`[data-tool=${tool}]`).click();await page.locator('#drawing').scrollIntoViewIfNeeded();const r=await page.locator('#drawing').boundingBox(),p=([x,y])=>({x:r.x+x*r.width/800,y:r.y+y*r.height/800});if(options.shift)await page.keyboard.down('Shift');let q=p(a);await page.mouse.move(q.x,q.y);await page.mouse.down();q=p(b);await page.mouse.move(q.x,q.y,{steps:options.steps||3});if(options.captureLoss)await page.locator('#drawingWrap').evaluate(el=>el.dispatchEvent(new PointerEvent('lostpointercapture',{pointerId:1,pointerType:'mouse',bubbles:true})));if(options.blur)await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();if(options.shift)await page.keyboard.up('Shift');}
async function rawDraft(){return page.evaluate(()=>new Promise((resolve,reject)=>{const open=indexedDB.open('trace3d-drafts',1);open.onsuccess=()=>{const db=open.result,tx=db.transaction('drafts','readonly'),read=tx.objectStore('drafts').get('current');read.onsuccess=()=>resolve(read.result);read.onerror=()=>reject(read.error);tx.oncomplete=()=>db.close();};}));}
try{
 await page.goto(url);await page.waitForFunction(()=>document.querySelectorAll('.part-item').length===4);assert.equal(await page.locator('[data-format]').count(),2);assert.equal(await page.locator('[data-format="3mf"]').count(),0);await blank();
 // The release point is sampled, sparse/dot strokes remain, capture/focus loss commits once.
 await drag('pen',[180,180],[450,240],{captureLoss:true});assert.equal(await page.locator('.part-item').count(),1);
 await drag('pencil',[200,320],[460,370],{blur:true});assert.equal(await page.locator('.part-item').count(),2);
 await drag('marker',[200,430],[202,430],{steps:1});assert.equal(await page.locator('.part-item').count(),3);
 await page.locator('#drawing').evaluate(el=>{const b=el.getBoundingClientRect();el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:91,pointerType:'mouse',button:0,clientX:b.x+b.width*.3,clientY:b.y+b.height*.65}));window.dispatchEvent(new PointerEvent('pointerup',{pointerId:91,pointerType:'mouse',button:0,clientX:b.x+b.width*.6,clientY:b.y+b.height*.7}));});let data=await project();assert.equal(data.shapes.length,4);assert.ok(data.shapes.at(-1).points.length>=2);assert.ok(data.shapes.at(-1).points.at(-1)[0]>=479);
 await blank();await drag('rectangle',[100,100],[340,260]);await page.locator('[data-color="#5ab3b1"]').click();await drag('ellipse',[180,160],[450,350],{shift:true});await drag('line',[100,400],[450,500]);data=await project();assert.deepEqual(data.shapes.map(s=>s.type),['rectangle','ellipse','line']);
 // Hidden layers leave the model/export; locked layers resist color, height, deletion and eraser.
 let rows=page.locator('.layer-row');await rows.last().locator('[data-action=visibility]').click();data=await project();assert.equal(data.shapes[0].visible,false);await page.locator('[data-format=obj]').click();{const event=page.waitForEvent('download');await page.locator('#exportModel').click();const d=await event,zip=await JSZip.loadAsync(await fs.readFile(await d.path()));const mtl=await zip.file(/\.mtl$/)[0].async('string');assert.ok(!mtl.includes('Kd 0.298039 0.196078 0.356863'));}
 await rows.last().locator('[data-action=visibility]').click();await rows.last().locator('.part-item').click();await rows.last().locator('[data-action=lock]').click();assert.equal(await page.locator('#deletePart').isDisabled(),true);assert.equal(await page.locator('#partColor').isDisabled(),true);await page.locator('#partHeight').evaluate(el=>{el.value='10';el.dispatchEvent(new Event('change'));});await page.locator('[data-color="#ed8078"]').click();data=await project();assert.equal(data.shapes[0].color,'#4c325b');assert.equal(data.shapes[0].height,undefined);
 const lockedPolygons=structuredClone(data.shapes[0].polygons);await drag('select',[140,140],[170,160]);data=await project();assert.deepEqual(data.shapes[0].polygons,lockedPolygons);await drag('erase',[140,140],[160,150]);assert.equal(await page.locator('.part-item').count(),3);await rows.last().locator('[data-action=lock]').click();
 // Reordering changes the actual color stack and is undoable.
 await rows.last().locator('[data-action=up]').click();data=await project();assert.deepEqual(data.shapes.map(s=>s.type),['ellipse','rectangle','line']);await page.locator('#undo').click();data=await project();assert.deepEqual(data.shapes.map(s=>s.type),['rectangle','ellipse','line']);await page.locator('#redo').click();
 await rows.first().locator('input[type=checkbox]').check();await rows.nth(1).locator('input[type=checkbox]').check();await page.locator('#groupLayers').click();await page.locator('#partHeight').fill('5');await page.locator('#partHeight').dispatchEvent('change');await page.locator('#projectName').fill('Herstel met lagen en foto');
 const png=await page.locator('#drawing').screenshot();await page.locator('#imageFile').setInputFiles({name:'voorbeeld.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>!document.getElementById('referenceOptions').hidden);await saved();const before=await rawDraft();assert.equal(before.project.version,3);assert.ok(before.project.reference.data.startsWith('data:image/'));await page.reload();await page.waitForFunction(()=>document.getElementById('autosaveStatus').textContent.includes('hersteld'));data=await project();assert.equal(data.name,'Herstel met lagen en foto');assert.equal(data.shapes.length,3);assert.equal(data.groups.length,1);assert.ok(data.shapes.some(s=>s.height===5));assert.equal(data.reference.name,'voorbeeld.png');
 // User replacement persists an empty design rather than reviving the previous drawing.
 await blank();await saved();await page.reload();await page.waitForFunction(()=>document.getElementById('autosaveStatus').textContent.includes('hersteld'));assert.equal(await page.locator('.part-item').count(),0);
 // Explicit close and endpoint snapping make an incomplete pen contour fillable.
 await page.locator('[data-tool=pen]').click();const b=await page.locator('#drawing').boundingBox(),coords=[[200,200],[500,200],[500,500],[200,500]];await page.mouse.move(b.x+b.width*.25,b.y+b.height*.25);await page.mouse.down();for(const [x,y] of coords.slice(1))await page.mouse.move(b.x+x*b.width/800,b.y+y*b.height/800,{steps:10});await page.mouse.up();await page.locator('.part-item').first().click();assert.equal(await page.locator('#closeLine').isDisabled(),false);await page.locator('#closeLine').click();data=await project();assert.equal(data.shapes[0].closed,true);await page.locator('[data-tool=fill]').click();await page.mouse.click(b.x+b.width*.4,b.y+b.height*.4);assert.equal(await page.locator('.part-item').count(),2);
 await blank();await page.locator('[data-tool=rectangle]').click();await page.locator('#shapeFilled').uncheck();await drag('rectangle',[180,180],[500,500]);await page.locator('[data-tool=fill]').click();await page.mouse.click(b.x+b.width*.4,b.y+b.height*.4);assert.equal(await page.locator('.part-item').count(),2);await saved();
 // Corrupt recovery is retained and downloadable until the user explicitly discards it.
 await page.evaluate(()=>new Promise(resolve=>{const open=indexedDB.open('trace3d-drafts',1);open.onsuccess=()=>{const db=open.result,tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put({project:{app:'invalid',name:'Bewaar deze kopie'},savedAt:Date.now()},'current');tx.oncomplete=()=>{db.close();resolve();};};}));await page.reload();await page.locator('#recoveryWarning').waitFor({state:'visible'});await page.locator('#projectName').fill('Nieuwe veilige naam');await page.waitForTimeout(400);assert.equal((await rawDraft()).project.name,'Bewaar deze kopie');{const event=page.waitForEvent('download');await page.locator('#downloadRecovery').click();const d=await event;assert.equal(JSON.parse(await fs.readFile(await d.path(),'utf8')).name,'Bewaar deze kopie');}await page.locator('#discardRecovery').click();await saved();assert.equal((await rawDraft()).project.name,'Nieuwe veilige naam');
 const denied=await browser.newPage({locale:'en-US'});denied.on('pageerror',e=>errors.push(e.message));await denied.addInitScript(()=>Object.defineProperty(window,'indexedDB',{value:undefined}));await denied.goto(url);await denied.waitForFunction(()=>document.querySelectorAll('.part-item').length===4);assert.ok((await denied.locator('#autosaveStatus').textContent()).includes('unavailable'));await denied.close();
 await fs.mkdir('tests/output',{recursive:true});await page.screenshot({path:'tests/output/editor-v03.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Editor browser checks passed: stroke retention/release, primitives/fill/close, visibility/export, locks/order/undo, IndexedDB image/group recovery, blank reset, corrupt recovery and unavailable storage.');
}finally{await browser.close();}
