import { t, initLanguages, number } from './i18n.js';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import JSZip from 'jszip';
import { initGeometry,SIZE,strokePolygons,normalizePaths,pointInside,boundsOf,modelData,bufferGeometry,binarySTL,objFiles,threeMFEntries,floodContours,offsetPaths } from './geometry.js';
async function startApp(){
await initGeometry();
initLanguages(()=>{syncInputs();render();updateParts();setTool(tool);setFormat(format);updateModel();});
const $=id=>document.getElementById(id);
const icon=(body)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons={pen:icon('<path d="m4 20 4-1 12-12a2.8 2.8 0 0 0-4-4L4 15z"/><path d="m14 5 5 5M4 15l4 4"/>'),marker:icon('<path d="m5 14 9-10 6 6-10 9z"/><path d="m5 14-3 5 5 3 3-3M14 4l2-2 6 6-2 2M2 22h7"/>'),pencil:icon('<path d="m3 21 3-8L17 2l5 5-11 11zM6 13l5 5M15 4l5 5M3 21l3-1"/>'),fill:icon('<path d="m8 3 10 10-7 7-9-9 7-7 1-2M3 11h15M19 14c0 0-3 4-3 5a3 3 0 0 0 6 0c0-1-3-5-3-5z"/>'),erase:icon('<path d="m10 3-8 9a2 2 0 0 0 0 3l6 6h5L23 9 13 2zM7 8l10 10M8 21h14"/>'),select:icon('<path d="M4 2v18l5-5 4 7 3-2-4-7h8z"/>'),undo:icon('<path d="M3 8h10a7 7 0 0 1 0 14M3 8l5-5M3 8l5 5"/>'),redo:icon('<path d="M21 8H11a7 7 0 0 0 0 14M21 8l-5-5M21 8l-5 5"/>'),grid:icon('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M15 3v18M3 9h18M3 15h18"/>'),image:icon('<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/>'),reset:icon('<path d="M3 8h5V3M3 8a9 9 0 1 1-1 8"/>'),download:icon('<path d="M12 3v12M7 10l5 5 5-5M4 16v5h16v-5"/>')};
const tools=[['pen','Pen','Teken een lijn. Sluit je vorm om hem te vullen.'],['marker','Stift','Maak brede lijnen met een stevige stift.'],['pencil','Potlood','Teken met een zachtere lijn. Stylusdruk bepaalt de dikte.'],['fill','Vullen','Klik in een gesloten ruimte of op een onderdeel om het te kleuren.'],['erase','Gum','Klik of veeg over een onderdeel om het te verwijderen.'],['select','Selecteer','Klik op een onderdeel. Sleep om te verplaatsen of kies een andere kleur.']];
const palette=['#4c325b','#5ab3b1','#fbbd30','#ed8078','#6994cf','#ffffff'];
let state={name:t('Mijn eerste ontwerp'),shapes:[],reference:null,width:80,thickness:3,groups:[]},selected=null,tool='pen',color=palette[0],size=8,format='stl',isDemo=true;
let history=[],future=[],referenceImg=null,dirty=false,toastTimer,modelTimer,model=null,scene,renderer,camera,controls,mesh,platform;
const canvas=$('drawing'),ctx=canvas.getContext('2d');canvas.width=canvas.height=1600;
let draft=null,gesture=null,spaceHeld=false,zoom=1,pan={x:0,y:0},pointers=new Map(),pinch=null,grid=true;
let checked=new Set();
const snapshot=()=>({...state,shapes:structuredClone(state.shapes),groups:structuredClone(state.groups||[]),selected,checked:[...checked]});
function selectionShapes(){return state.shapes.filter(s=>checked.has(s.id)||s.id===selected);}
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function toast(text){$('toast').textContent=t(text);$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200);}
function beginEdit(){return snapshot();}
function finishEdit(before){history.push(before);if(history.length>40)history.shift();future=[];dirty=true;isDemo=false;render();updateParts();scheduleModel();updateHistory();}
function restore(s){state={name:s.name,shapes:structuredClone(s.shapes),reference:s.reference,width:s.width,thickness:s.thickness,groups:structuredClone(s.groups||[])};selected=s.selected||null;checked=new Set(s.checked||[]);syncInputs();loadReferenceImage();render();updateParts();scheduleModel();updateHistory();dirty=true;isDemo=false;}
function updateHistory(){$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());}
function setTool(nextTool){tool=nextTool;document.querySelectorAll('[data-tool]').forEach(b=>{const active=b.dataset.tool===tool;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});$('toolHint').textContent=t(tools.find(x=>x[0]===tool)[2]);for(const [id,label] of tools){const b=document.querySelector(`[data-tool=${id}]`);if(b){b.title=t(label);b.querySelector('span').textContent=t(label);}}canvas.style.cursor=tool==='select'?'default':tool==='erase'?'cell':'crosshair';if(tool!=='select'){selected=null;checked.clear();updateParts();render();}}
for(const [id,label] of tools){const b=document.createElement('button');b.className='tool-button';b.dataset.tool=id;b.title=t(label);b.innerHTML=icons[id]+`<span>${t(label)}</span>`;b.addEventListener('click',()=>setTool(id));$('tools').append(b);}
for(const c of palette){const b=document.createElement('button');b.className='swatch';b.style.background=c;b.dataset.color=c;b.setAttribute('aria-label',`Kleur ${c}`);b.addEventListener('click',()=>changeColor(c));$('palette').insertBefore(b,$('color'));}
function changeColor(c){color=c;$('color').value=c;document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('active',b.dataset.color===c);b.setAttribute('aria-pressed',b.dataset.color===c);});if(selected){const before=beginEdit(),shape=state.shapes.find(s=>s.id===selected);if(shape){for(const part of selectionShapes())part.color=c;finishEdit(before);}}}
$('color').addEventListener('input',e=>changeColor(e.target.value));
$('partColor').addEventListener('change',e=>changeColor(e.target.value));
$('brushSize').addEventListener('input',e=>{size=+e.target.value;$('brushSizeLabel').textContent=`${size} px`;});
$('undo').innerHTML=icons.undo;$('redo').innerHTML=icons.redo;$('gridToggle').innerHTML=icons.grid;$('reset3d').innerHTML=icons.reset;$('imageIcon').innerHTML=icons.image;
$('undo').onclick=undo;$('redo').onclick=redo;
function polygonPath(context,polygons){context.beginPath();for(const ring of polygons){if(!ring.length)continue;context.moveTo(...ring[0]);for(let i=1;i<ring.length;i++)context.lineTo(...ring[i]);context.closePath();}}
function drawShapes(context,shapes){for(const s of shapes){polygonPath(context,s.polygons);context.fillStyle=s.color;context.globalAlpha=1;context.fill('nonzero');}}
function render(){ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,SIZE,SIZE);if(referenceImg&&state.reference){const scale=Math.min(720/referenceImg.width,720/referenceImg.height),w=referenceImg.width*scale,h=referenceImg.height*scale;ctx.globalAlpha=state.reference.opacity/100;ctx.drawImage(referenceImg,(SIZE-w)/2,(SIZE-h)/2,w,h);ctx.globalAlpha=1;}
 drawShapes(ctx,state.shapes);if(draft&&draft.points.length)drawShapes(ctx,[{polygons:strokePolygons(draft.points,draft.tool,draft.size),color:draft.color}]);
 if(selected){const parts=selectionShapes();if(parts.length){const polygons=parts.flatMap(s=>s.polygons);polygonPath(ctx,polygons);ctx.save();ctx.strokeStyle='#6d94ce';ctx.lineWidth=2.5;ctx.setLineDash([8,5]);ctx.stroke();const b=boundsOf(polygons);ctx.strokeRect(b.minX-5,b.minY-5,b.width+10,b.height+10);ctx.restore();}}
 $('canvasBadge').textContent=t(isDemo?'Voorbeeldontwerp':state.reference?'Je afbeelding overtrekken':'Jouw ontwerp');$('drawingCount').textContent=t(state.shapes.length===1?'{count} onderdeel':'{count} onderdelen',{count:number(state.shapes.length)});
}
function hit(point){for(let i=state.shapes.length-1;i>=0;i--)if(pointInside(state.shapes[i].polygons,...point))return state.shapes[i];return null;}
function point(event){const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(SIZE,(event.clientX-r.left)/r.width*SIZE)),Math.max(0,Math.min(SIZE,(event.clientY-r.top)/r.height*SIZE)),event.pointerType==='pen'?Math.max(.08,event.pressure||.5):.5,event.pointerType==='pen'?1:0];}
function updateView(){$('paper').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('fitView').textContent=`${Math.round(zoom*100)}%`;$('paper').classList.toggle('grid',grid);}
function changeZoom(value){zoom=Math.max(.5,Math.min(4,value));updateView();}
$('zoomOut').onclick=()=>changeZoom(zoom/1.25);$('zoomIn').onclick=()=>changeZoom(zoom*1.25);$('fitView').onclick=()=>{zoom=1;pan={x:0,y:0};updateView();};$('gridToggle').onclick=()=>{grid=!grid;updateView();$('gridToggle').setAttribute('aria-pressed',grid);};
const wrap=$('drawingWrap');
function startInput(e){if(e.button!==0&&e.button!==1)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(pointers.size===2){if(gesture?.before){state.shapes=structuredClone(gesture.before.shapes);selected=gesture.before.selected;}draft=null;gesture=null;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},pan:{...pan}};render();return;}
 if(pointers.size>1)return;
 const rect=canvas.getBoundingClientRect(),onPaper=e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom;
 if(spaceHeld||e.button===1||!onPaper){gesture={type:'pan',start:{x:e.clientX,y:e.clientY},pan:{...pan},pointerId:e.pointerId};return;}
 const p=point(e);
 if(['pen','marker','pencil'].includes(tool)){if(state.shapes.length>=300){toast('Dit project heeft 300 onderdelen. Verwijder een onderdeel om verder te tekenen.');return;}draft={points:[p],tool,color,size};gesture={type:'draw',before:beginEdit(),pointerId:e.pointerId};selected=null;}
 else if(tool==='select'){const s=hit(p);checked.clear();if(s?.groupId)checked=new Set(state.shapes.filter(part=>part.groupId===s.groupId).map(part=>part.id));selected=s?.id||null;updateParts();render();if(s)gesture={type:'move',pointerId:e.pointerId,start:p,members:selectionShapes().map(part=>({id:part.id,polygons:structuredClone(part.polygons)})),before:beginEdit()};}
 else if(tool==='erase'){gesture={type:'erase',pointerId:e.pointerId,before:beginEdit(),changed:false};eraseAt(p);}
 else if(tool==='fill'){fillAt(p);}
}
function eraseAt(p){const s=hit(p);if(s){state.shapes=state.shapes.filter(x=>x.id!==s.id);if(selected===s.id)selected=null;gesture.changed=true;render();}}
function moveInput(e){if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size>=2){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};zoom=Math.max(.5,Math.min(4,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance)));pan={x:pinch.pan.x+center.x-pinch.center.x,y:pinch.pan.y+center.y-pinch.center.y};updateView();return;}
 if(!gesture||gesture.pointerId!==e.pointerId)return;const p=point(e);
 if(gesture.type==='draw'&&draft){const coalesced=e.getCoalescedEvents?.();for(const event of (coalesced?.length?coalesced:[e])){const q=point(event),prev=draft.points.at(-1);if(Math.hypot(q[0]-prev[0],q[1]-prev[1])>.8)draft.points.push(q);}render();}
 else if(gesture.type==='pan'){pan={x:gesture.pan.x+e.clientX-gesture.start.x,y:gesture.pan.y+e.clientY-gesture.start.y};updateView();}
 else if(gesture.type==='erase')eraseAt(p);
  else if(gesture.type==='move'){const bounds=boundsOf(gesture.members.flatMap(s=>s.polygons)),dx=Math.max(-bounds.minX,Math.min(SIZE-bounds.maxX,p[0]-gesture.start[0])),dy=Math.max(-bounds.minY,Math.min(SIZE-bounds.maxY,p[1]-gesture.start[1]));for(const member of gesture.members){const part=state.shapes.find(s=>s.id===member.id);if(part)part.polygons=member.polygons.map(r=>r.map(([x,y])=>[x+dx,y+dy]));}gesture.moved=Math.abs(dx)+Math.abs(dy)>.5;render();}
}
function endPointer(e,cancelled=false){pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;gesture=null;draft=null;return;}if(!gesture||gesture.pointerId!==e.pointerId)return;const g=gesture;gesture=null;if(cancelled){if(g.before){state.shapes=structuredClone(g.before.shapes);selected=g.before.selected;}draft=null;render();updateParts();return;}
 if(g.type==='draw'&&draft){if(draft.points.length>8){const first=draft.points[0],last=draft.points.at(-1);if(Math.hypot(first[0]-last[0],first[1]-last[1])<Math.max(draft.size*1.2,13))draft.points.push([...first]);}
 const polygons=strokePolygons(draft.points,draft.tool,draft.size);if(polygons.length){state.shapes.push({id:uid(),name:`${t(tools.find(t=>t[0]===draft.tool)[1])} ${state.shapes.filter(s=>s.type===draft.tool).length+1}`,type:draft.tool,color:draft.color,size:draft.size,polygons});}draft=null;finishEdit(g.before);}
 else if((g.type==='erase'&&g.changed)||(g.type==='move'&&g.moved))finishEdit(g.before);else render();
}
// iOS finger input uses Touch Events; ignore companion Pointer Events to avoid duplicates.
const useTouchEvents='ontouchstart' in window||navigator.maxTouchPoints>0;
const ignorePointer=e=>useTouchEvents&&e.pointerType==='touch';
wrap.addEventListener('pointerdown',e=>{if(ignorePointer(e))return;startInput(e);if(pointers.has(e.pointerId)){try{wrap.setPointerCapture(e.pointerId);}catch{ /* Window listeners also track uncaptured input. */ }}});
window.addEventListener('pointermove',e=>{if(!ignorePointer(e))moveInput(e);});
window.addEventListener('pointerup',e=>{if(!ignorePointer(e))endPointer(e);});
window.addEventListener('pointercancel',e=>{if(!ignorePointer(e))endPointer(e,true);});
wrap.addEventListener('lostpointercapture',e=>{if(!ignorePointer(e)&&pointers.has(e.pointerId))endPointer(e,true);});
function touchInput(touch,event){return {pointerId:`touch-${touch.identifier}`,pointerType:touch.touchType==='stylus'?'pen':'touch',pressure:touch.force||.5,button:0,clientX:touch.clientX,clientY:touch.clientY,target:event.target,preventDefault(){}};}
function handleTouches(event,action){if(!useTouchEvents)return;const touches=[...event.changedTouches].filter(t=>!(t.touchType==='stylus'&&window.PointerEvent));if(!touches.length)return;if(event.cancelable)event.preventDefault();for(const touch of touches)action(touchInput(touch,event));}
wrap.addEventListener('touchstart',e=>handleTouches(e,startInput),{passive:false});
wrap.addEventListener('touchmove',e=>handleTouches(e,moveInput),{passive:false});
wrap.addEventListener('touchend',e=>handleTouches(e,input=>{moveInput(input);endPointer(input);}),{passive:false});
wrap.addEventListener('touchcancel',e=>handleTouches(e,input=>endPointer(input,true)),{passive:false});
for(const type of ['gesturestart','gesturechange'])wrap.addEventListener(type,e=>{if(e.cancelable)e.preventDefault();},{passive:false});
wrap.addEventListener('wheel',e=>{e.preventDefault();changeZoom(zoom*Math.exp(-e.deltaY*.001));},{passive:false});
function fillAt(p){const before=beginEdit(),existing=hit(p);if(existing){existing.color=color;selected=existing.id;finishEdit(before);return;}
 const res=640,mask=document.createElement('canvas');mask.width=mask.height=res;const mc=mask.getContext('2d',{willReadFrequently:true});mc.scale(res/SIZE,res/SIZE);drawShapes(mc,state.shapes);const bytes=mc.getImageData(0,0,res,res).data,alpha=new Uint8Array(res*res);for(let i=0;i<alpha.length;i++)alpha[i]=bytes[i*4+3];
 const polygons=floodContours(alpha,res,p[0]*res/SIZE,p[1]*res/SIZE);if(!polygons?.length){toast('Sluit eerst je lijnen. Vullen werkt binnen een gesloten ruimte.');return;}if(state.shapes.length>=300){toast('Je project heeft al 300 onderdelen.');return;}
 // A small overlap closes raster/vector seams; it does not enter the image reference.
 const shape={id:uid(),name:`${t('Vullen')} ${state.shapes.filter(s=>s.type==='fill').length+1}`,type:'fill',color,polygons:offsetPaths(polygons,1)};state.shapes.unshift(shape);selected=shape.id;finishEdit(before);
}
function updateParts(){
 checked=new Set([...checked].filter(id=>state.shapes.some(s=>s.id===id)));
 $('partsList').replaceChildren();$('partsCount').textContent=state.shapes.length;
 if(!state.shapes.length){const p=document.createElement('p');p.className='parts-empty';p.textContent=t('Teken je eerste lijn om te beginnen.');$('partsList').append(p);}
 const members=selectionShapes(),ids=new Set(members.map(s=>s.id));
 const display=[...state.shapes].reverse(),seen=new Set();
 for(const s of display){
  if(s.groupId&&!seen.has(s.groupId)){seen.add(s.groupId);const group=state.groups?.find(g=>g.id===s.groupId);const heading=document.createElement('button');heading.className='group-heading';heading.textContent=group?.name||t('Groep');heading.onclick=()=>{setTool('select');selected=s.id;checked=new Set(state.shapes.filter(p=>p.groupId===s.groupId).map(p=>p.id));updateParts();render();};$('partsList').append(heading);}
  if(s.groupId&&display.find(p=>p.groupId===s.groupId)?.id!==s.id)continue;
  const layers=s.groupId?display.filter(p=>p.groupId===s.groupId):[s];
  for(const layer of layers){const row=document.createElement('div');row.className='layer-row'+(layer.groupId?' grouped':'');const check=document.createElement('input');check.type='checkbox';check.checked=checked.has(layer.id);check.setAttribute('aria-label',t('Laag selecteren')+': '+layer.name);check.onchange=()=>{if(check.checked){setTool('select');checked.add(layer.id);selected=layer.id;}else{checked.delete(layer.id);if(selected===layer.id)selected=[...checked].at(-1)||null;}updateParts();render();};const b=document.createElement('button');b.className=`part-item${ids.has(layer.id)?' selected':''}`;b.setAttribute('aria-pressed',ids.has(layer.id));const dot=document.createElement('span');dot.className='part-dot';dot.style.background=layer.color;const name=document.createElement('span');name.textContent=layer.nameKey?t(layer.nameKey):layer.name;const type=document.createElement('span');type.className='part-type';type.textContent=number(layer.height??state.thickness)+' mm';b.append(dot,name,type);b.onclick=()=>{setTool('select');checked.clear();selected=layer.id;color=layer.color;$('color').value=color;updateParts();render();};row.append(check,b);$('partsList').append(row);}
 }
 const shape=state.shapes.find(s=>s.id===selected);$('selectedActions').hidden=!shape;
 if(shape){$('partColor').value=shape.color;const heights=members.map(s=>s.height??state.thickness);$('partHeight').value=heights.every(h=>h===heights[0])?heights[0]:'';$('partHeight').placeholder=t('Verschillende hoogtes');}
 $('groupLayers').disabled=checked.size<2;$('ungroupLayers').disabled=!members.some(s=>s.groupId);
}
function removeSelected(){if(!selected)return;const before=beginEdit(),ids=new Set(selectionShapes().map(s=>s.id));state.shapes=state.shapes.filter(s=>!ids.has(s.id));cleanupGroups();selected=null;checked.clear();finishEdit(before);}
function cleanupGroups(){state.groups=(state.groups||[]).filter(g=>state.shapes.some(s=>s.groupId===g.id));}
$('groupLayers').onclick=()=>{if(checked.size<2)return;const before=beginEdit(),id=uid();state.groups??=[];state.groups.push({id,name:t('Groep')+' '+(state.groups.length+1)});for(const s of state.shapes)if(checked.has(s.id))s.groupId=id;cleanupGroups();finishEdit(before);};
$('ungroupLayers').onclick=()=>{const before=beginEdit(),groups=new Set(selectionShapes().map(s=>s.groupId).filter(Boolean));for(const s of state.shapes)if(groups.has(s.groupId))delete s.groupId;cleanupGroups();finishEdit(before);};
$('partHeight').onchange=()=>{const value=+$('partHeight').value;if(!Number.isFinite(value)||value<.6||value>20){toast(t('Kies een hoogte van 0,6–20 mm.'));updateParts();return;}const before=beginEdit();for(const s of selectionShapes())s.height=value;finishEdit(before);};
$('defaultHeight').onclick=()=>{const before=beginEdit();for(const s of selectionShapes())delete s.height;finishEdit(before);};
$('deletePart').onclick=removeSelected;
function syncInputs(){$('projectName').value=state.name;$('modelWidth').value=state.width;$('modelThickness').value=state.thickness;$('referenceOptions').hidden=!state.reference;$('referenceName').textContent=state.reference?.name||t('Laad een foto of tekening als voorbeeld.');if(state.reference){$('referenceOpacity').value=state.reference.opacity;$('opacityLabel').textContent=`${state.reference.opacity}%`;}}
$('projectName').addEventListener('input',e=>{state.name=e.target.value;dirty=true;});
function dimensionsChanged(){const w=+$('modelWidth').value,h=+$('modelThickness').value;if(!Number.isFinite(w)||!Number.isFinite(h)||w<10||w>250||h<.6||h>20){toast('Kies een breedte van 10–250 mm en een dikte van 0,6–20 mm.');syncInputs();return;}const before=beginEdit();state.width=w;state.thickness=h;finishEdit(before);}
$('modelWidth').addEventListener('change',dimensionsChanged);$('modelThickness').addEventListener('change',dimensionsChanged);
function scheduleModel(){clearTimeout(modelTimer);modelTimer=setTimeout(updateModel,180);}
function init3d(){try{const host=$('preview3d');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0xf2eef6,1);host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Draaibaar 3D-voorbeeld van je ontwerp');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.1,2000);camera.up.set(0,0,1);camera.position.set(90,-140,145);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.enablePan=false;controls.minDistance=20;controls.maxDistance=650;controls.addEventListener('change',render3d);scene.add(new THREE.HemisphereLight(0xffffff,0xffffff,1.7));const light=new THREE.DirectionalLight(0xffffff,1.4);light.position.set(-80,-70,130);scene.add(light);const rim=new THREE.DirectionalLight(0xffffff,1);rim.position.set(80,50,60);scene.add(rim);new ResizeObserver(()=>{const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();render3d();}).observe(host);}catch(e){$('previewUnavailable').hidden=false;renderer=null;console.warn('3D preview unavailable',e);}}
function render3d(){if(renderer)renderer.render(scene,camera);}
function reset3d(){if(!controls)return;const max=model?Math.max(model.width,model.height):80;camera.position.set(max*.95,-max*1.5,max*1.35);controls.target.set(0,0,(model?.thickness||3)/2);controls.update();render3d();}
function updateModel(){try{model=modelData(state.shapes,state.width,state.thickness,true);$('exportModel').disabled=!model;$('previewEmpty').hidden=!!model||!renderer;
 if(model){$('modelSize').textContent=`${number(model.width)} × ${number(model.height)} × ${number(model.thickness)} mm`;const warnings=[];if(model.islands>1)warnings.push(t('{count} losse vormen: deze worden afzonderlijke printonderdelen. Verbind ze met overlappende lijnen voor één geheel.',{count:number(model.islands)}));const thin=state.shapes.some(s=>s.size&&s.size*(s.type==='marker'?1.7:s.type==='pencil'?.35:1)*model.scale<.8);if(thin)warnings.push(t('Er zijn dunne lijnen. Gebruik een dikkere lijn of maak je model groter.'));$('printNotice').hidden=!warnings.length;$('printNotice').textContent=warnings.join(' ');}else{$('modelSize').textContent=t('Nog geen model');$('printNotice').hidden=true;}
 if(renderer){if(mesh){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();mesh=null;}if(platform){scene.remove(platform);platform.geometry.dispose();platform.material.dispose();platform=null;}if(model){mesh=new THREE.Mesh(bufferGeometry(model),new THREE.MeshStandardMaterial({vertexColors:true,roughness:.8,metalness:0}));scene.add(mesh);const max=Math.max(model.width,model.height);platform=new THREE.Mesh(new THREE.CylinderGeometry(max*.72,max*.72,1,80),new THREE.MeshStandardMaterial({color:0xe5ddeb,roughness:.8}));platform.rotation.x=Math.PI/2;platform.position.z=-1.8;scene.add(platform);reset3d();}render3d();}
 }catch(e){console.error(e);$('exportModel').disabled=true;toast('Het 3D-model kon niet worden opgebouwd. Maak je laatste stap ongedaan en probeer opnieuw.');}}
$('reset3d').onclick=reset3d;$('refresh3d').onclick=updateModel;
function filename(){return (state.name||'mijn-ontwerp').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)||'mijn-ontwerp';}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function setFormat(f){format=f;document.querySelectorAll('[data-format]').forEach(b=>{const active=b.dataset.format===f;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});const labels={stl:'STL downloaden',obj:'OBJ-pakket downloaden','3mf':'3MF downloaden'};$('exportModel').innerHTML=icons.download;const label=document.createElement('span');label.textContent=t(labels[f]);$('exportModel').append(label);$('exportInfo').textContent=t(f==='stl'?'STL bevat geen kleuren. Open het bestand in je slicer.':f==='obj'?'Pak de ZIP uit en houd OBJ en MTL bij elkaar. Sommige slicers negeren OBJ-kleuren: gebruik dan 3MF.':'Importeer als één object met meerdere onderdelen. Controleer de kleuren en wijs filamenten toe in Bambu Studio/Orca.');}
for(const b of document.querySelectorAll('[data-format]'))b.onclick=()=>setFormat(b.dataset.format);
$('exportModel').onclick=async()=>{const button=$('exportModel');button.disabled=true;try{await new Promise(r=>requestAnimationFrame(r));const name=filename(),data=modelData(state.shapes,state.width,state.thickness,true);if(!data)throw new Error('empty');if(format==='stl')download(new Blob([binarySTL(data)],{type:'model/stl'}),`${name}.stl`);else{const zip=new JSZip();if(format==='3mf'){for(const [path,content] of Object.entries(threeMFEntries(data,state.name)))zip.file(path,content);download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${name}.3mf`);}else{const files=objFiles(data,name);zip.file(`${name}.obj`,files.obj);zip.file(`${name}.mtl`,files.mtl);zip.file('README.txt',t('Pak de ZIP uit en houd OBJ en MTL bij elkaar. Sommige slicers negeren OBJ-kleuren: gebruik dan 3MF.')+'\n'+t('Importeer als één object met meerdere onderdelen. Controleer de kleuren en wijs filamenten toe in Bambu Studio/Orca.'));download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${name}-OBJ.zip`);}}toast(t('Je 3D-bestand is klaar. Veel plezier met printen!'));}catch(e){console.error(e);toast(t('Exporteren is niet gelukt. Probeer het ontwerp kleiner of eenvoudiger te maken.'));}finally{button.disabled=!state.shapes.length;}};
$('saveProject').onclick=()=>{download(new Blob([JSON.stringify({app:'3dindeklas-trace3d',version:2,...state},null,2)],{type:'application/json'}),`${filename()}.trace3d.json`);dirty=false;toast('Project opgeslagen. Je kunt het later weer openen en aanpassen.');};
async function confirmReplace(action,title){if(!dirty&&!state.shapes.length){action();return;}$('confirmTitle').textContent=t(title);$('confirmText').textContent=t('Je huidige ontwerp wordt vervangen. Sla je project eerst op als je het wilt bewaren.');$('confirmDialog').showModal();const accept=()=>{cleanup();action();},cancel=()=>cleanup();function cleanup(){$('confirmDialog').close();$('acceptConfirm').removeEventListener('click',accept);$('cancelConfirm').removeEventListener('click',cancel);$('confirmDialog').removeEventListener('cancel',cancel);}$('acceptConfirm').addEventListener('click',accept);$('cancelConfirm').addEventListener('click',cancel);$('confirmDialog').addEventListener('cancel',cancel);}
function newProject(){state={name:t('Mijn ontwerp'),shapes:[],reference:null,width:80,thickness:3,groups:[]};selected=null;checked.clear();history=[];future=[];dirty=false;isDemo=false;referenceImg=null;zoom=1;pan={x:0,y:0};syncInputs();updateView();render();updateParts();updateHistory();updateModel();setTool('pen');}
$('newProject').onclick=()=>confirmReplace(newProject,'Een nieuw ontwerp beginnen?');
$('openProject').onclick=()=>$('projectFile').click();
function validateProject(data){if(data.app!=='3dindeklas-trace3d'||![1,2].includes(data.version))throw new Error('Dit is geen geldig Trace3D-project.');if(typeof data.name!=='string'||data.name.length>80||!Array.isArray(data.shapes)||data.shapes.length>300||!Number.isFinite(data.width)||data.width<10||data.width>250||!Number.isFinite(data.thickness)||data.thickness<.6||data.thickness>20)throw new Error('Het project bevat ongeldige instellingen.');let pointCount=0;
 const groups=(data.groups||[]);if(!Array.isArray(groups)||groups.length>300||groups.some(g=>typeof g.id!=='string'||typeof g.name!=='string'||g.name.length>100))throw new Error('Het project bevat ongeldige groepen.');const groupMap=new Map(groups.map(g=>[g.id,uid()]));
 const shapes=data.shapes.map(s=>{if(typeof s.id!=='string'||typeof s.name!=='string'||s.name.length>100||!/^#[0-9a-f]{6}$/i.test(s.color)||!['pen','marker','pencil','fill'].includes(s.type)||!Array.isArray(s.polygons)||s.polygons.length>1000)throw new Error('Het project bevat een ongeldig onderdeel.');const polygons=s.polygons.map(p=>{if(!Array.isArray(p)||p.length<3||p.length>20000)throw new Error('Een vorm bevat te veel punten.');pointCount+=p.length;if(pointCount>150000)throw new Error('Het project is te groot.');return p.map(q=>{if(!Array.isArray(q)||q.length!==2||!q.every(n=>Number.isFinite(n)&&Math.abs(n)<=10000))throw new Error('Het project bevat een ongeldig punt.');return [...q];});});if(s.height!==undefined&&(!Number.isFinite(s.height)||s.height<.6||s.height>20))throw new Error('Het project bevat een ongeldige hoogte.');if(s.groupId!==undefined&&!groupMap.has(s.groupId))throw new Error('Het project bevat ongeldige groepen.');return {id:uid(),name:s.name,type:s.type,color:s.color.toLowerCase(),polygons,...(s.height!==undefined?{height:s.height}:{}),...(s.groupId?{groupId:groupMap.get(s.groupId)}:{}),...(Number.isFinite(s.size)&&s.size>0&&s.size<=100?{size:s.size}:{})};});
 let reference=null;if(data.reference){const r=data.reference;if(typeof r.name!=='string'||r.name.length>250||typeof r.data!=='string'||r.data.length>12000000||!/^data:image\/(png|jpeg|webp|gif|bmp);base64,[A-Za-z0-9+/=\r\n]+$/.test(r.data)||!Number.isFinite(r.opacity)||r.opacity<0||r.opacity>100)throw new Error('De opgeslagen afbeelding is ongeldig.');reference={name:r.name,data:r.data,opacity:r.opacity};}return {name:data.name,shapes,reference,width:data.width,thickness:data.thickness,groups:groups.map(g=>({id:groupMap.get(g.id),name:g.name}))};
}
$('projectFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>18000000)throw new Error('Dit projectbestand is te groot.');const data=validateProject(JSON.parse(await file.text()));confirmReplace(()=>{state=data;selected=null;checked.clear();history=[];future=[];dirty=false;isDemo=false;zoom=1;pan={x:0,y:0};syncInputs();updateView();loadReferenceImage();updateParts();updateHistory();updateModel();toast('Je project is geopend.');},'Project openen?');}catch(err){toast(err instanceof SyntaxError?'Dit bestand is geen geldig project.':err.message);}});
$('uploadImage').onclick=()=>$('imageFile').click();
function loadReferenceImage(){referenceImg=null;if(state.reference){const img=new Image();const expected=state.reference.data;img.onload=()=>{if(state.reference?.data===expected){referenceImg=img;render();}};img.onerror=()=>toast('De opgeslagen afbeelding kon niet worden gelezen.');img.src=state.reference.data;}syncInputs();render();}
$('imageFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20000000)throw new Error('Kies een afbeelding van maximaal 20 MB.');if(!/^image\/(png|jpeg|webp|gif|bmp)$/.test(file.type))throw new Error('Gebruik een PNG, JPG, WebP, GIF of BMP-afbeelding.');const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('Deze afbeelding kon niet worden gelezen.'));img.src=url;});const factor=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),temp=document.createElement('canvas');temp.width=Math.round(img.naturalWidth*factor);temp.height=Math.round(img.naturalHeight*factor);temp.getContext('2d').drawImage(img,0,0,temp.width,temp.height);const before=beginEdit();state.reference={name:file.name.slice(0,250),data:temp.toDataURL(file.type==='image/jpeg'?'image/jpeg':'image/png',.9),opacity:35};finishEdit(before);loadReferenceImage();toast('Afbeelding ingeladen. Je kunt hem nu overtrekken.');}finally{URL.revokeObjectURL(url);}}catch(err){toast(err.message);}});
$('referenceOpacity').addEventListener('input',e=>{if(!state.reference)return;state.reference={...state.reference,opacity:+e.target.value};$('opacityLabel').textContent=`${e.target.value}%`;dirty=true;render();});
$('removeImage').onclick=()=>{const before=beginEdit();state.reference=null;referenceImg=null;finishEdit(before);syncInputs();};
$('help').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>$('helpDialog').close());
function demo(){const star=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?129:245;star.push([400+Math.cos(a)*r,410+Math.sin(a)*r]);}const hole=[];for(let i=47;i>=0;i--){const a=i/48*Math.PI*2;hole.push([400+Math.cos(a)*18,239+Math.sin(a)*18]);}
 const inner=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?48:91;inner.push([400+Math.cos(a)*r,424+Math.sin(a)*r]);}
 const ring=p=>normalizePaths([...offsetPaths([p],7),...offsetPaths([p],-7).map(r=>r.reverse())]);
 const border=ring(star),circle=[...hole].reverse(),holeBorder=normalizePaths([...offsetPaths([circle],4),...offsetPaths([circle],-4).map(r=>r.reverse())]);
 state={name:t('Mijn eerste ontwerp'),shapes:[{id:uid(),name:'Gele ster',nameKey:'Gele ster',type:'fill',color:'#fbbd30',polygons:normalizePaths([star,hole])},{id:uid(),name:'Paarse rand',nameKey:'Paarse rand',type:'pen',color:'#4c325b',size:14,polygons:border},{id:uid(),name:'Ophangoog',nameKey:'Ophangoog',type:'pen',color:'#4c325b',size:8,polygons:holeBorder},{id:uid(),name:'Turquoise ster',nameKey:'Turquoise ster',type:'fill',color:'#5ab3b1',polygons:normalizePaths([inner])}],reference:null,width:80,thickness:3,groups:[]};selected=null;checked.clear();history=[];future=[];dirty=false;isDemo=true;referenceImg=null;zoom=1;pan={x:0,y:0};syncInputs();updateView();render();updateParts();updateHistory();updateModel();}
$('loadDemo').onclick=()=>isDemo&&!dirty?demo():confirmReplace(demo,'Het voorbeeld openen?');
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected();}else if(e.code==='Space'){spaceHeld=true;e.preventDefault();canvas.style.cursor='grab';}else{const shortcuts={p:'pen',m:'marker',b:'pencil',f:'fill',e:'erase',v:'select'};if(shortcuts[e.key.toLowerCase()])setTool(shortcuts[e.key.toLowerCase()]);}});
window.addEventListener('keyup',e=>{if(e.code==='Space'){spaceHeld=false;canvas.style.cursor=tool==='select'?'default':'crosshair';}});window.addEventListener('blur',()=>{spaceHeld=false;pointers.clear();pinch=null;gesture=null;draft=null;});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
// The browser agent API, when supported, uses the same actions as the visible editor.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const definition of [{name:'read_trace3d_design',title:'Ontwerp bekijken',description:'Read the current drawing dimensions and part count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {name:state.name,parts:state.shapes.length,width:state.width,thickness:state.thickness};}},{name:'configure_trace3d_dimensions',title:'Printafmetingen instellen',description:'Set drawing width and extrusion thickness in millimeters.',inputSchema:{type:'object',properties:{width:{type:'number',minimum:10,maximum:250},thickness:{type:'number',minimum:.6,maximum:20}},required:['width','thickness'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isFinite(input.width)||input.width<10||input.width>250||!Number.isFinite(input.thickness)||input.thickness<.6||input.thickness>20)throw new Error('Invalid dimensions');$('modelWidth').value=input.width;$('modelThickness').value=input.thickness;dimensionsChanged();updateModel();return {width:state.width,thickness:state.thickness};}}]){try{Promise.resolve(document.modelContext.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
setTool('pen');changeColor(color);setFormat('stl');init3d();demo();

}
startApp().catch(error=>{console.error(error);document.getElementById('previewUnavailable').hidden=false;document.getElementById('previewUnavailable').textContent=t('Het 3D-model kon niet worden opgebouwd. Maak je laatste stap ongedaan en probeer opnieuw.');document.getElementById('exportModel').disabled=true;});
