import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import JSZip from 'jszip';
import { SIZE,strokePolygons,normalizePaths,pointInside,boundsOf,modelData,bufferGeometry,binarySTL,objFiles,floodContours,offsetPaths } from './geometry.js';
const $=id=>document.getElementById(id);
const icon=(body)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons={pen:icon('<path d="m4 20 4-1 12-12a2.8 2.8 0 0 0-4-4L4 15z"/><path d="m14 5 5 5M4 15l4 4"/>'),marker:icon('<path d="m5 14 9-10 6 6-10 9z"/><path d="m5 14-3 5 5 3 3-3M14 4l2-2 6 6-2 2M2 22h7"/>'),pencil:icon('<path d="m3 21 3-8L17 2l5 5-11 11zM6 13l5 5M15 4l5 5M3 21l3-1"/>'),fill:icon('<path d="m8 3 10 10-7 7-9-9 7-7 1-2M3 11h15M19 14c0 0-3 4-3 5a3 3 0 0 0 6 0c0-1-3-5-3-5z"/>'),erase:icon('<path d="m10 3-8 9a2 2 0 0 0 0 3l6 6h5L23 9 13 2zM7 8l10 10M8 21h14"/>'),select:icon('<path d="M4 2v18l5-5 4 7 3-2-4-7h8z"/>'),undo:icon('<path d="M3 8h10a7 7 0 0 1 0 14M3 8l5-5M3 8l5 5"/>'),redo:icon('<path d="M21 8H11a7 7 0 0 0 0 14M21 8l-5-5M21 8l-5 5"/>'),grid:icon('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M15 3v18M3 9h18M3 15h18"/>'),image:icon('<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/>'),reset:icon('<path d="M3 8h5V3M3 8a9 9 0 1 1-1 8"/>'),download:icon('<path d="M12 3v12M7 10l5 5 5-5M4 16v5h16v-5"/>')};
const tools=[['pen','Pen','Teken een lijn. Sluit je vorm om hem te vullen.'],['marker','Stift','Maak brede lijnen met een stevige stift.'],['pencil','Potlood','Teken met een zachtere lijn. Stylusdruk bepaalt de dikte.'],['fill','Vullen','Klik in een gesloten ruimte of op een onderdeel om het te kleuren.'],['erase','Gum','Klik of veeg over een onderdeel om het te verwijderen.'],['select','Selecteer','Klik op een onderdeel. Sleep om te verplaatsen of kies een andere kleur.']];
const palette=['#4c325b','#5ab3b1','#fbbd30','#ed8078','#6994cf','#ffffff'];
let state={name:'Mijn eerste ontwerp',shapes:[],reference:null,width:80,thickness:3},selected=null,tool='pen',color=palette[0],size=8,format='stl',isDemo=true;
let history=[],future=[],referenceImg=null,dirty=false,toastTimer,modelTimer,model=null,scene,renderer,camera,controls,mesh,platform;
const canvas=$('drawing'),ctx=canvas.getContext('2d');canvas.width=canvas.height=1600;
let draft=null,gesture=null,spaceHeld=false,zoom=1,pan={x:0,y:0},pointers=new Map(),pinch=null,grid=true;
const snapshot=()=>({...state,shapes:structuredClone(state.shapes),selected});
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200);}
function beginEdit(){return snapshot();}
function finishEdit(before){history.push(before);if(history.length>40)history.shift();future=[];dirty=true;isDemo=false;render();updateParts();scheduleModel();updateHistory();}
function restore(s){state={name:s.name,shapes:structuredClone(s.shapes),reference:s.reference,width:s.width,thickness:s.thickness};selected=s.selected||null;syncInputs();loadReferenceImage();render();updateParts();scheduleModel();updateHistory();dirty=true;isDemo=false;}
function updateHistory(){$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop());}
function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop());}
function setTool(t){tool=t;document.querySelectorAll('[data-tool]').forEach(b=>{const active=b.dataset.tool===tool;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});$('toolHint').textContent=tools.find(x=>x[0]===tool)[2];canvas.style.cursor=tool==='select'?'default':tool==='erase'?'cell':'crosshair';if(tool!=='select'){selected=null;updateParts();render();}}
for(const [id,label] of tools){const b=document.createElement('button');b.className='tool-button';b.dataset.tool=id;b.title=label;b.innerHTML=icons[id]+`<span>${label}</span>`;b.addEventListener('click',()=>setTool(id));$('tools').append(b);}
for(const c of palette){const b=document.createElement('button');b.className='swatch';b.style.background=c;b.dataset.color=c;b.setAttribute('aria-label',`Kleur ${c}`);b.addEventListener('click',()=>changeColor(c));$('palette').insertBefore(b,$('color'));}
function changeColor(c){color=c;$('color').value=c;document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('active',b.dataset.color===c);b.setAttribute('aria-pressed',b.dataset.color===c);});if(selected){const before=beginEdit(),shape=state.shapes.find(s=>s.id===selected);if(shape){shape.color=c;finishEdit(before);}}}
$('color').addEventListener('input',e=>changeColor(e.target.value));
$('partColor').addEventListener('change',e=>changeColor(e.target.value));
$('brushSize').addEventListener('input',e=>{size=+e.target.value;$('brushSizeLabel').textContent=`${size} px`;});
$('undo').innerHTML=icons.undo;$('redo').innerHTML=icons.redo;$('gridToggle').innerHTML=icons.grid;$('reset3d').innerHTML=icons.reset;$('imageIcon').innerHTML=icons.image;
$('undo').onclick=undo;$('redo').onclick=redo;
function polygonPath(context,polygons){context.beginPath();for(const ring of polygons){if(!ring.length)continue;context.moveTo(...ring[0]);for(let i=1;i<ring.length;i++)context.lineTo(...ring[i]);context.closePath();}}
function drawShapes(context,shapes){for(const s of shapes){polygonPath(context,s.polygons);context.fillStyle=s.color;context.globalAlpha=1;context.fill('nonzero');}}
function render(){ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,SIZE,SIZE);if(referenceImg&&state.reference){const scale=Math.min(720/referenceImg.width,720/referenceImg.height),w=referenceImg.width*scale,h=referenceImg.height*scale;ctx.globalAlpha=state.reference.opacity/100;ctx.drawImage(referenceImg,(SIZE-w)/2,(SIZE-h)/2,w,h);ctx.globalAlpha=1;}
 drawShapes(ctx,state.shapes);if(draft&&draft.points.length)drawShapes(ctx,[{polygons:strokePolygons(draft.points,draft.tool,draft.size),color:draft.color}]);
 if(selected){const s=state.shapes.find(s=>s.id===selected);if(s){polygonPath(ctx,s.polygons);ctx.save();ctx.strokeStyle='#6d94ce';ctx.lineWidth=2.5;ctx.setLineDash([8,5]);ctx.stroke();const b=boundsOf(s.polygons);ctx.strokeRect(b.minX-5,b.minY-5,b.width+10,b.height+10);ctx.restore();}}
 $('canvasBadge').textContent=isDemo?'Voorbeeldontwerp':state.reference?'Je afbeelding overtrekken':'Jouw ontwerp';$('drawingCount').textContent=`${state.shapes.length} ${state.shapes.length===1?'onderdeel':'onderdelen'}`;
}
function hit(point){for(let i=state.shapes.length-1;i>=0;i--)if(pointInside(state.shapes[i].polygons,...point))return state.shapes[i];return null;}
function point(event){const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(SIZE,(event.clientX-r.left)/r.width*SIZE)),Math.max(0,Math.min(SIZE,(event.clientY-r.top)/r.height*SIZE)),event.pointerType==='pen'?Math.max(.08,event.pressure||.5):.5,event.pointerType==='pen'?1:0];}
function updateView(){$('paper').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('fitView').textContent=`${Math.round(zoom*100)}%`;$('paper').classList.toggle('grid',grid);}
function changeZoom(value){zoom=Math.max(.5,Math.min(4,value));updateView();}
$('zoomOut').onclick=()=>changeZoom(zoom/1.25);$('zoomIn').onclick=()=>changeZoom(zoom*1.25);$('fitView').onclick=()=>{zoom=1;pan={x:0,y:0};updateView();};$('gridToggle').onclick=()=>{grid=!grid;updateView();$('gridToggle').setAttribute('aria-pressed',grid);};
const wrap=$('drawingWrap');
wrap.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;e.preventDefault();wrap.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(pointers.size===2){if(gesture?.before){state.shapes=structuredClone(gesture.before.shapes);selected=gesture.before.selected;}draft=null;gesture=null;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},pan:{...pan}};render();return;}
 if(pointers.size>1)return;
 if(spaceHeld||e.button===1||e.target!==canvas){gesture={type:'pan',start:{x:e.clientX,y:e.clientY},pan:{...pan},pointerId:e.pointerId};return;}
 const p=point(e);
 if(['pen','marker','pencil'].includes(tool)){if(state.shapes.length>=300){toast('Dit project heeft 300 onderdelen. Verwijder een onderdeel om verder te tekenen.');return;}draft={points:[p],tool,color,size};gesture={type:'draw',before:beginEdit(),pointerId:e.pointerId};selected=null;}
 else if(tool==='select'){const s=hit(p);selected=s?.id||null;updateParts();render();if(s)gesture={type:'move',pointerId:e.pointerId,start:p,polygons:structuredClone(s.polygons),before:beginEdit()};}
 else if(tool==='erase'){gesture={type:'erase',pointerId:e.pointerId,before:beginEdit(),changed:false};eraseAt(p);}
 else if(tool==='fill'){fillAt(p);}
});
function eraseAt(p){const s=hit(p);if(s){state.shapes=state.shapes.filter(x=>x.id!==s.id);if(selected===s.id)selected=null;gesture.changed=true;render();}}
wrap.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size>=2){const [a,b]=[...pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};zoom=Math.max(.5,Math.min(4,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance)));pan={x:pinch.pan.x+center.x-pinch.center.x,y:pinch.pan.y+center.y-pinch.center.y};updateView();return;}
 if(!gesture||gesture.pointerId!==e.pointerId)return;const p=point(e);
 if(gesture.type==='draw'&&draft){for(const event of (e.getCoalescedEvents?.()?.length?e.getCoalescedEvents():[e])){const q=point(event),prev=draft.points.at(-1);if(Math.hypot(q[0]-prev[0],q[1]-prev[1])>.8)draft.points.push(q);}render();}
 else if(gesture.type==='pan'){pan={x:gesture.pan.x+e.clientX-gesture.start.x,y:gesture.pan.y+e.clientY-gesture.start.y};updateView();}
 else if(gesture.type==='erase')eraseAt(p);
 else if(gesture.type==='move'){const s=state.shapes.find(s=>s.id===selected);if(s){const bounds=boundsOf(gesture.polygons),dx=Math.max(-bounds.minX,Math.min(SIZE-bounds.maxX,p[0]-gesture.start[0])),dy=Math.max(-bounds.minY,Math.min(SIZE-bounds.maxY,p[1]-gesture.start[1]));s.polygons=gesture.polygons.map(r=>r.map(([x,y])=>[x+dx,y+dy]));gesture.moved=Math.abs(dx)+Math.abs(dy)>.5;render();}}
});
function endPointer(e,cancelled=false){pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;gesture=null;draft=null;return;}if(!gesture||gesture.pointerId!==e.pointerId)return;const g=gesture;gesture=null;if(cancelled){if(g.before){state.shapes=structuredClone(g.before.shapes);selected=g.before.selected;}draft=null;render();updateParts();return;}
 if(g.type==='draw'&&draft){if(draft.points.length>8){const first=draft.points[0],last=draft.points.at(-1);if(Math.hypot(first[0]-last[0],first[1]-last[1])<Math.max(draft.size*1.2,13))draft.points.push([...first]);}
 const polygons=strokePolygons(draft.points,draft.tool,draft.size);if(polygons.length){state.shapes.push({id:uid(),name:`${tools.find(t=>t[0]===draft.tool)[1]} ${state.shapes.filter(s=>s.type===draft.tool).length+1}`,type:draft.tool,color:draft.color,size:draft.size,polygons});}draft=null;finishEdit(g.before);}
 else if((g.type==='erase'&&g.changed)||(g.type==='move'&&g.moved))finishEdit(g.before);else render();
}
wrap.addEventListener('pointerup',e=>endPointer(e));wrap.addEventListener('pointercancel',e=>endPointer(e,true));wrap.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))endPointer(e,true);});
wrap.addEventListener('wheel',e=>{e.preventDefault();changeZoom(zoom*Math.exp(-e.deltaY*.001));},{passive:false});
function fillAt(p){const before=beginEdit(),existing=hit(p);if(existing){existing.color=color;selected=existing.id;finishEdit(before);return;}
 const res=640,mask=document.createElement('canvas');mask.width=mask.height=res;const mc=mask.getContext('2d',{willReadFrequently:true});mc.scale(res/SIZE,res/SIZE);drawShapes(mc,state.shapes);const bytes=mc.getImageData(0,0,res,res).data,alpha=new Uint8Array(res*res);for(let i=0;i<alpha.length;i++)alpha[i]=bytes[i*4+3];
 const polygons=floodContours(alpha,res,p[0]*res/SIZE,p[1]*res/SIZE);if(!polygons?.length){toast('Sluit eerst je lijnen. Vullen werkt binnen een gesloten ruimte.');return;}if(state.shapes.length>=300){toast('Je project heeft al 300 onderdelen.');return;}
 // A small overlap closes raster/vector seams; it does not enter the image reference.
 const shape={id:uid(),name:`Vulling ${state.shapes.filter(s=>s.type==='fill').length+1}`,type:'fill',color,polygons:offsetPaths(polygons,1)};state.shapes.unshift(shape);selected=shape.id;finishEdit(before);
}
function updateParts(){$('partsList').replaceChildren();$('partsCount').textContent=state.shapes.length;if(!state.shapes.length){const p=document.createElement('p');p.className='parts-empty';p.textContent='Teken je eerste lijn om te beginnen.';$('partsList').append(p);}
 for(const s of [...state.shapes].reverse()){const b=document.createElement('button');b.className=`part-item${selected===s.id?' selected':''}`;b.setAttribute('aria-pressed',selected===s.id);const dot=document.createElement('span');dot.className='part-dot';dot.style.background=s.color;const name=document.createElement('span');name.textContent=s.name;const type=document.createElement('span');type.className='part-type';type.textContent=s.type==='fill'?'vorm':'lijn';b.append(dot,name,type);b.onclick=()=>{setTool('select');selected=s.id;color=s.color;$('color').value=color;updateParts();render();};$('partsList').append(b);}
 const shape=state.shapes.find(s=>s.id===selected);$('selectedActions').hidden=!shape;if(shape)$('partColor').value=shape.color;
}
function removeSelected(){if(!selected)return;const before=beginEdit();state.shapes=state.shapes.filter(s=>s.id!==selected);selected=null;finishEdit(before);}
$('deletePart').onclick=removeSelected;
function syncInputs(){$('projectName').value=state.name;$('modelWidth').value=state.width;$('modelThickness').value=state.thickness;$('referenceOptions').hidden=!state.reference;$('referenceName').textContent=state.reference?.name||'Laad een foto of tekening als voorbeeld.';if(state.reference){$('referenceOpacity').value=state.reference.opacity;$('opacityLabel').textContent=`${state.reference.opacity}%`;}}
$('projectName').addEventListener('input',e=>{state.name=e.target.value;dirty=true;});
function dimensionsChanged(){const w=+$('modelWidth').value,h=+$('modelThickness').value;if(!Number.isFinite(w)||!Number.isFinite(h)||w<10||w>250||h<.6||h>20){toast('Kies een breedte van 10–250 mm en een dikte van 0,6–20 mm.');syncInputs();return;}const before=beginEdit();state.width=w;state.thickness=h;finishEdit(before);}
$('modelWidth').addEventListener('change',dimensionsChanged);$('modelThickness').addEventListener('change',dimensionsChanged);
function scheduleModel(){clearTimeout(modelTimer);modelTimer=setTimeout(updateModel,180);}
function colorCanvas(){const temp=document.createElement('canvas');temp.width=temp.height=1600;const context=temp.getContext('2d');context.scale(2,2);context.fillStyle='#ffffff';context.fillRect(0,0,SIZE,SIZE);drawShapes(context,state.shapes);return temp;}
function init3d(){try{const host=$('preview3d');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0xf2eef6,1);host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Draaibaar 3D-voorbeeld van je ontwerp');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.1,2000);camera.up.set(0,0,1);camera.position.set(90,-140,145);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.enablePan=false;controls.minDistance=20;controls.maxDistance=650;controls.addEventListener('change',render3d);scene.add(new THREE.HemisphereLight(0xffffff,0x4c325b,2.8));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-80,-70,130);scene.add(light);const rim=new THREE.DirectionalLight(0xffffff,1);rim.position.set(80,50,60);scene.add(rim);new ResizeObserver(()=>{const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();render3d();}).observe(host);}catch(e){$('previewUnavailable').hidden=false;renderer=null;console.warn('3D preview unavailable',e);}}
function render3d(){if(renderer)renderer.render(scene,camera);}
function reset3d(){if(!controls)return;const max=model?Math.max(model.width,model.height):80;camera.position.set(max*.95,-max*1.5,max*1.35);controls.target.set(0,0,(model?.thickness||3)/2);controls.update();render3d();}
function updateModel(){try{model=modelData(state.shapes,state.width,state.thickness,true);$('exportModel').disabled=!model;$('previewEmpty').hidden=!!model||!renderer;
 if(model){$('modelSize').textContent=`${model.width.toFixed(1).replace('.',',')} × ${model.height.toFixed(1).replace('.',',')} × ${state.thickness.toString().replace('.',',')} mm`;const warnings=[];if(model.islands>1)warnings.push(`${model.islands} losse vormen: deze worden afzonderlijke printonderdelen. Verbind ze met overlappende lijnen voor één geheel.`);const thin=state.shapes.some(s=>s.size&&s.size*(s.type==='marker'?1.7:s.type==='pencil'?.35:1)*model.scale<.8);if(thin)warnings.push('Er zijn dunne lijnen. Gebruik een dikkere lijn of maak je model groter.');$('printNotice').hidden=!warnings.length;$('printNotice').textContent=warnings.join(' ');}else{$('modelSize').textContent='Nog geen model';$('printNotice').hidden=true;}
 if(renderer){if(mesh){scene.remove(mesh);mesh.geometry.dispose();for(const material of mesh.material){material.map?.dispose();material.dispose();}mesh=null;}if(platform){scene.remove(platform);platform.geometry.dispose();platform.material.dispose();platform=null;}if(model){const texture=new THREE.CanvasTexture(colorCanvas());texture.colorSpace=THREE.SRGBColorSpace;mesh=new THREE.Mesh(bufferGeometry(model),[new THREE.MeshStandardMaterial({map:texture,roughness:.42,metalness:.03}),new THREE.MeshStandardMaterial({vertexColors:true,roughness:.42,metalness:.03})]);scene.add(mesh);const max=Math.max(model.width,model.height);platform=new THREE.Mesh(new THREE.CylinderGeometry(max*.72,max*.72,1,80),new THREE.MeshStandardMaterial({color:0xe5ddeb,roughness:.8}));platform.rotation.x=Math.PI/2;platform.position.z=-1.8;scene.add(platform);reset3d();}render3d();}
 }catch(e){console.error(e);$('exportModel').disabled=true;toast('Het 3D-model kon niet worden opgebouwd. Maak je laatste stap ongedaan en probeer opnieuw.');}}
$('reset3d').onclick=reset3d;$('refresh3d').onclick=updateModel;
function filename(){return (state.name||'mijn-ontwerp').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)||'mijn-ontwerp';}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function setFormat(f){format=f;document.querySelectorAll('[data-format]').forEach(b=>{const active=b.dataset.format===f;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});$('exportModel').innerHTML=icons.download+`<span>${f==='stl'?'STL downloaden':'OBJ-pakket downloaden'}</span>`;$('exportInfo').textContent=f==='stl'?'Open het STL-bestand in je slicer om je print voor te bereiden. STL bevat geen kleuren.':'Je krijgt een ZIP met een OBJ-, MTL- en kleuren-PNG-bestand. Houd deze bij elkaar. Kies bij het importeren millimeters.';}
for(const b of document.querySelectorAll('[data-format]'))b.onclick=()=>setFormat(b.dataset.format);
$('exportModel').onclick=async()=>{const button=$('exportModel');button.disabled=true;try{await new Promise(r=>requestAnimationFrame(r));const name=filename();if(format==='stl'){const solid=modelData(state.shapes,state.width,state.thickness,false);if(!solid)throw new Error('empty');download(new Blob([binarySTL(solid)],{type:'model/stl'}),`${name}.stl`);}else{const colored=modelData(state.shapes,state.width,state.thickness,true);if(!colored)throw new Error('empty');const textureName=`${name}-kleuren.png`,files=objFiles(colored,name,textureName),zip=new JSZip();const textureBlob=await new Promise(resolve=>colorCanvas().toBlob(resolve,'image/png'));zip.file(textureName,await textureBlob.arrayBuffer());zip.file(`${name}.obj`,files.obj);zip.file(`${name}.mtl`,files.mtl);zip.file('LEESMIJ.txt','3dindeklas · Teken naar 3D\n\nBewaar OBJ, MTL en de kleuren-PNG in dezelfde map. Importeer het model in millimeters.\nKleuren zijn materiaalgegevens; de daadwerkelijke printkleur hangt af van je filament en slicer.\n');download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${name}-OBJ.zip`);}toast('Je 3D-bestand is klaar. Veel plezier met printen!');}catch(e){console.error(e);toast('Exporteren is niet gelukt. Probeer het ontwerp kleiner of eenvoudiger te maken.');}finally{button.disabled=!state.shapes.length;}};
$('saveProject').onclick=()=>{download(new Blob([JSON.stringify({app:'3dindeklas-trace3d',version:1,...state},null,2)],{type:'application/json'}),`${filename()}.trace3d.json`);dirty=false;toast('Project opgeslagen. Je kunt het later weer openen en aanpassen.');};
async function confirmReplace(action,title){if(!dirty&&!state.shapes.length){action();return;}$('confirmTitle').textContent=title;$('confirmText').textContent='Je huidige ontwerp wordt vervangen. Sla je project eerst op als je het wilt bewaren.';$('confirmDialog').showModal();const accept=()=>{cleanup();action();},cancel=()=>cleanup();function cleanup(){$('confirmDialog').close();$('acceptConfirm').removeEventListener('click',accept);$('cancelConfirm').removeEventListener('click',cancel);$('confirmDialog').removeEventListener('cancel',cancel);}$('acceptConfirm').addEventListener('click',accept);$('cancelConfirm').addEventListener('click',cancel);$('confirmDialog').addEventListener('cancel',cancel);}
function newProject(){state={name:'Mijn ontwerp',shapes:[],reference:null,width:80,thickness:3};selected=null;history=[];future=[];dirty=false;isDemo=false;referenceImg=null;zoom=1;pan={x:0,y:0};syncInputs();updateView();render();updateParts();updateHistory();updateModel();setTool('pen');}
$('newProject').onclick=()=>confirmReplace(newProject,'Een nieuw ontwerp beginnen?');
$('openProject').onclick=()=>$('projectFile').click();
function validateProject(data){if(data.app!=='3dindeklas-trace3d'||data.version!==1)throw new Error('Dit is geen geldig Trace3D-project.');if(typeof data.name!=='string'||data.name.length>80||!Array.isArray(data.shapes)||data.shapes.length>300||!Number.isFinite(data.width)||data.width<10||data.width>250||!Number.isFinite(data.thickness)||data.thickness<.6||data.thickness>20)throw new Error('Het project bevat ongeldige instellingen.');let pointCount=0;
 const shapes=data.shapes.map(s=>{if(typeof s.id!=='string'||typeof s.name!=='string'||s.name.length>100||!/^#[0-9a-f]{6}$/i.test(s.color)||!['pen','marker','pencil','fill'].includes(s.type)||!Array.isArray(s.polygons)||s.polygons.length>1000)throw new Error('Het project bevat een ongeldig onderdeel.');const polygons=s.polygons.map(p=>{if(!Array.isArray(p)||p.length<3||p.length>20000)throw new Error('Een vorm bevat te veel punten.');pointCount+=p.length;if(pointCount>150000)throw new Error('Het project is te groot.');return p.map(q=>{if(!Array.isArray(q)||q.length!==2||!q.every(n=>Number.isFinite(n)&&Math.abs(n)<=10000))throw new Error('Het project bevat een ongeldig punt.');return [...q];});});return {id:uid(),name:s.name,type:s.type,color:s.color.toLowerCase(),polygons,...(Number.isFinite(s.size)&&s.size>0&&s.size<=100?{size:s.size}:{})};});
 let reference=null;if(data.reference){const r=data.reference;if(typeof r.name!=='string'||r.name.length>250||typeof r.data!=='string'||r.data.length>12000000||!/^data:image\/(png|jpeg|webp|gif|bmp);base64,[A-Za-z0-9+/=\r\n]+$/.test(r.data)||!Number.isFinite(r.opacity)||r.opacity<0||r.opacity>100)throw new Error('De opgeslagen afbeelding is ongeldig.');reference={name:r.name,data:r.data,opacity:r.opacity};}return {name:data.name,shapes,reference,width:data.width,thickness:data.thickness};
}
$('projectFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>18000000)throw new Error('Dit projectbestand is te groot.');const data=validateProject(JSON.parse(await file.text()));confirmReplace(()=>{state=data;selected=null;history=[];future=[];dirty=false;isDemo=false;zoom=1;pan={x:0,y:0};syncInputs();updateView();loadReferenceImage();updateParts();updateHistory();updateModel();toast('Je project is geopend.');},'Project openen?');}catch(err){toast(err instanceof SyntaxError?'Dit bestand is geen geldig project.':err.message);}});
$('uploadImage').onclick=()=>$('imageFile').click();
function loadReferenceImage(){referenceImg=null;if(state.reference){const img=new Image();const expected=state.reference.data;img.onload=()=>{if(state.reference?.data===expected){referenceImg=img;render();}};img.onerror=()=>toast('De opgeslagen afbeelding kon niet worden gelezen.');img.src=state.reference.data;}syncInputs();render();}
$('imageFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>20000000)throw new Error('Kies een afbeelding van maximaal 20 MB.');if(!/^image\/(png|jpeg|webp|gif|bmp)$/.test(file.type))throw new Error('Gebruik een PNG, JPG, WebP, GIF of BMP-afbeelding.');const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('Deze afbeelding kon niet worden gelezen.'));img.src=url;});const factor=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),temp=document.createElement('canvas');temp.width=Math.round(img.naturalWidth*factor);temp.height=Math.round(img.naturalHeight*factor);temp.getContext('2d').drawImage(img,0,0,temp.width,temp.height);const before=beginEdit();state.reference={name:file.name.slice(0,250),data:temp.toDataURL(file.type==='image/jpeg'?'image/jpeg':'image/png',.9),opacity:35};finishEdit(before);loadReferenceImage();toast('Afbeelding ingeladen. Je kunt hem nu overtrekken.');}finally{URL.revokeObjectURL(url);}}catch(err){toast(err.message);}});
$('referenceOpacity').addEventListener('input',e=>{if(!state.reference)return;state.reference={...state.reference,opacity:+e.target.value};$('opacityLabel').textContent=`${e.target.value}%`;dirty=true;render();});
$('removeImage').onclick=()=>{const before=beginEdit();state.reference=null;referenceImg=null;finishEdit(before);syncInputs();};
$('help').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>$('helpDialog').close());
function demo(){const star=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?129:245;star.push([400+Math.cos(a)*r,410+Math.sin(a)*r]);}const hole=[];for(let i=47;i>=0;i--){const a=i/48*Math.PI*2;hole.push([400+Math.cos(a)*18,239+Math.sin(a)*18]);}
 const inner=[];for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?48:91;inner.push([400+Math.cos(a)*r,424+Math.sin(a)*r]);}
 const ring=p=>normalizePaths([...offsetPaths([p],7),...offsetPaths([p],-7).map(r=>r.reverse())]);
 const border=ring(star),circle=[...hole].reverse(),holeBorder=normalizePaths([...offsetPaths([circle],4),...offsetPaths([circle],-4).map(r=>r.reverse())]);
 state={name:'Mijn eerste ontwerp',shapes:[{id:uid(),name:'Gele ster',type:'fill',color:'#fbbd30',polygons:normalizePaths([star,hole])},{id:uid(),name:'Paarse rand',type:'pen',color:'#4c325b',size:14,polygons:border},{id:uid(),name:'Ophangoog',type:'pen',color:'#4c325b',size:8,polygons:holeBorder},{id:uid(),name:'Turquoise ster',type:'fill',color:'#5ab3b1',polygons:normalizePaths([inner])}],reference:null,width:80,thickness:3};selected=null;history=[];future=[];dirty=false;isDemo=true;referenceImg=null;zoom=1;pan={x:0,y:0};syncInputs();updateView();render();updateParts();updateHistory();updateModel();}
$('loadDemo').onclick=()=>confirmReplace(demo,'Het voorbeeld openen?');
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected();}else if(e.code==='Space'){spaceHeld=true;e.preventDefault();canvas.style.cursor='grab';}else{const shortcuts={p:'pen',m:'marker',b:'pencil',f:'fill',e:'erase',v:'select'};if(shortcuts[e.key.toLowerCase()])setTool(shortcuts[e.key.toLowerCase()]);}});
window.addEventListener('keyup',e=>{if(e.code==='Space'){spaceHeld=false;canvas.style.cursor=tool==='select'?'default':'crosshair';}});window.addEventListener('blur',()=>{spaceHeld=false;pointers.clear();pinch=null;gesture=null;draft=null;});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
// The browser agent API, when supported, uses the same actions as the visible editor.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const definition of [{name:'read_trace3d_design',title:'Ontwerp bekijken',description:'Read the current drawing dimensions and part count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {name:state.name,parts:state.shapes.length,width:state.width,thickness:state.thickness};}},{name:'configure_trace3d_dimensions',title:'Printafmetingen instellen',description:'Set drawing width and extrusion thickness in millimeters.',inputSchema:{type:'object',properties:{width:{type:'number',minimum:10,maximum:250},thickness:{type:'number',minimum:.6,maximum:20}},required:['width','thickness'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isFinite(input.width)||input.width<10||input.width>250||!Number.isFinite(input.thickness)||input.thickness<.6||input.thickness>20)throw new Error('Invalid dimensions');$('modelWidth').value=input.width;$('modelThickness').value=input.thickness;dimensionsChanged();updateModel();return {width:state.width,thickness:state.thickness};}}]){try{Promise.resolve(document.modelContext.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
setTool('pen');changeColor(color);setFormat('stl');init3d();demo();
